# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MyFirstiOSApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirstiOSApp
  pod 'SteviaLayout', '~> 4.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'ws', '~> 3.0'

end
